server:
  port: 8081

spring:
  application:
    name: local

  jpa:
    properties:
      hibernate:
        ddl-auto: update
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    bank-a:
      url: jdbc:postgresql://localhost:5432/bank_a
      username: admin
      password: admin
      driver-class-name: org.postgresql.Driver
    bank-b:
      url: jdbc:postgresql://localhost:5432/bank_b
      username: admin
      password: admin
      driver-class-name: org.postgresql.Driver

  activemq:
    broker-url: tcp://localhost:61616
    user: gunenv
    password: gunenv

  jms:
    listener:
      destination-name: accountBankQueue

logging:
  level:
    com.atomikos: WARN

    # Pour configurer la journalisation des transactions, si nécessaire
    org:
      springframework:
        transaction: DEBUG
        orm:
          jpa: DEBUG
    hibernate:
      SQL: DEBUG
      transaction: DEBUG
